-- Supabase Schema for Portal

-- Admins Table
CREATE TABLE IF NOT EXISTS public.admins (
    username TEXT PRIMARY KEY,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'admin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- App Config Table
CREATE TABLE IF NOT EXISTS public.app_config (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Shortcuts Table
CREATE TABLE IF NOT EXISTS public.shortcuts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant TEXT NOT NULL DEFAULT 'default',
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    icon_url TEXT,
    icon_64 TEXT,
    icon_128 TEXT,
    icon_256 TEXT,
    parent_label TEXT,
    child_label TEXT,
    favorite SMALLINT DEFAULT 0,
    clicks INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sort_index INTEGER DEFAULT 0,
    UNIQUE(name, url, tenant)
);

-- Label Colors Table
CREATE TABLE IF NOT EXISTS public.label_colors (
    name TEXT NOT NULL,
    tenant TEXT NOT NULL DEFAULT 'default',
    color_class TEXT,
    PRIMARY KEY(name, tenant)
);

-- Click Logs Table
CREATE TABLE IF NOT EXISTS public.click_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shortcut_id BIGINT REFERENCES public.shortcuts(id) ON DELETE CASCADE,
    clicked_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Image Search Logs
CREATE TABLE IF NOT EXISTS public.image_search_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_ip TEXT,
    user_agent TEXT,
    file_size INTEGER,
    file_type TEXT,
    filename TEXT,
    searched_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create a storage bucket for temp images
-- Note: You can also create this through the Supabase UI
-- INSERT INTO storage.buckets (id, name, public) VALUES ('temp_images', 'temp_images', true);

-- Insert default admin if table is empty (admin / miniappadmin)
-- Only run if needed
-- INSERT INTO public.admins (username, password_hash, role) 
-- VALUES ('admin', 'd530188ef6ef7331ea07ae086603a110a30b4da48d56b0d91295fcfa24fcf37d', 'superadmin')
-- ON CONFLICT (username) DO NOTHING;
